def revc(s):
    t = s[::-1]
    p = []
    for i in t:
        p.append(i)
    q = []
    for i in p:
        if(i == 'A'):
            q.append('T')
        elif(i == 'T'):
            q.append('A')
        elif(i == 'G'):
            q.append('C')
        else:
            q.append('G')
    st = ''.join(i for i in q)
    return st

a = 'GCGCGCATTTCATTGTCAGAAACTGGTAAGATCATTCATGGGGTGTCTGTTCGCTGGCTCGGGCTTGATTCAGGGCGTGCGCATCCGCTGCGTAAATTCCATAGTGAGAAGCCCTGTCCTAATGACCTTCATAACAACAGCAAGAGGTCCTGGCCGACAGTCGTCGCGGGGCCAGAGCCGATTAAGGTATATCATCGGATTGCCTGATGAAGCGTAAGGTTCAGGAGTGCGGGGTACCTAACCCTAGGGCCATCAGGACCAGGTAATAAATCAGCCTCTCTGAGGCATCTCTTGGGCAGAGAGAAAACTGCTACACAACAATACCGGGTGTCATCTATGCGTACAACCTTCGCTGGGCCGCCTATCACCCCCATACCTTAAACGCAGTTACCAATCGGTACGAATGGTCATAAGACGACTTAGTTCGCTTTTCGAGGATAGCAAATACCATGACTAAGACTCGCCTTTAACTAGTTAAAGTCGCTTGCAAGGCTTTCATATAGGTTGCACGTTTCCTAGCACGAATTATATAAGCAATTATCCGCTCATGAATCAGCATCCGAAGGCGTTACGTGAACCCTGTCCCACCTCGCAATAGTCATAAAGGGTTGGCCTGAGCTGTGCGATGTCGGCTAAAGTCACATATTTATAAGTCACTAGGAGGCGTCATGGGAAACTAATAAGACAACTATTCCCAAGCCTCAGAATAGGCGCCAAGCTCACGTCAATCGTGGCCGTATAGTCATTGTGTCGTAACGCATAGCCTAGACTCGGGGGGTTTGACACGAGTCTGCTCTAGTAACGGAAAACTCTCGGCCGCGATTACTTTCGATGTGGCATCGGGGCGAATGGTCGTGTAGACATGGTTTAGCCCTAGGTGGCACTCGAATGCGTCAACCAGTTAAAGATATTTCCACATACGGTATCGGATGGTATAATCCGCG'
l = []
for i in range(4,13):
    for index in range(len(a)):
        al = a[index:index+i]
        if(len(al) == i):
            if(al == revc(al)):
                #print(a[index:index+i])
                print((index+1),i)
